name: CI/CD with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Package, Build, and Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Package
        run: mvn -B package --file pom.xml -DskipTests
      - name: Build
        run: mvn clean install -DskipTests
      - name: Test
        run: mvn test